# Generated by Django 6.0 on 2026-01-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('greetings_text', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
