# Generated by Django 5.1.3 on 2026-01-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0005_alter_category_id_alter_education_id_alter_home_id_and_more",
        ),
        ("portfolio", "0005_contact"),
    ]

    operations = []
