# Generated by Django 6.0 on 2026-01-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
