# Generated by Django 6.0 on 2026-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_home_email_address_home_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='sub_heading',
            field=models.CharField(default='I am a Full Stack Developer', max_length=200),
        ),
    ]
