# Generated by Django 5.1.3 on 2026-01-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_contact_id"),
        ("portfolio", "0008_home_sub_heading"),
    ]

    operations = []
