# Generated by Django 5.1.3 on 2026-01-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_merge_0007_alter_contact_id_0008_home_sub_heading"),
        ("portfolio", "0010_alter_category_name"),
    ]

    operations = []
