# Generated by Django 5.1.3 on 2026-01-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_merge_20260125_1632"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "points",
                    models.TextField(
                        help_text="Enter bullet points separated by a new line or pipe |"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome icon class (e.g., 'fas fa-code')",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="home",
            name="github_url",
        ),
        migrations.AddField(
            model_name="home",
            name="about_summary",
            field=models.TextField(
                blank=True,
                help_text="A quick 2-line bio for the About page",
                max_length=500,
                null=True,
            ),
        ),
    ]
