# Generated by Django 6.0 on 2026-02-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_home_github_url_alter_aboutsection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='header_title',
            field=models.CharField(default='Sudalaiyandi', help_text='Text to display in the header/navigation bar', max_length=100),
        ),
    ]
